org: ahmed404
service: appsync-backend

frameworkVersion: "2"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev

  # Enabling AWS Node.js connection reuse improves performance by reducing latency and resource consumption,
  # as it allows multiple requests to use the same TCP connection, rather than opening new ones each time.
  # This leads to cost savings, better scalability, and helps prevent socket exhaustion in high-concurrency environments,
  # making the application more efficient overall.

  AWS_CONNECTION_REUSE_ENABLED: "1"

plugins:
  - serverless-appsync-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  appSync:
    - ${file(serverless.appsync-api.yml)}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tag:
          - Key: Name
            Value: UsersTable
          - Key: Environment
            Value: ${self:custom.stage}

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: web
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
        PreventUserExistenceErrors: ENABLED

  Outputs:
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool
